/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    colors: {
      extraDarkPurple: "#581c87",
      darkPurple: "#7e22ce",
      purple: "#9333ea",
      lightPurple: "#c084fc",
      dimPurple: "#f3e8ff",
      white: "#FFFFFF",
      black: "#000000",
      error: "#dc2626",
      gray: "#9ca3af",
      lightGray: "#d1d5db",
      dimGray: "#f3f4f6",
      ["light-gray"]: "#f9fafb",
      ["blue-0"]: "#EFF6FF",
      ["blue-1"]: "#DBEAFE",
      ["blue-2"]: "#BFDBFE",
      ["blue-3"]: "#93C5FD",
      ["blue-4"]: "#60A5FA",
      ["blue-5"]: "#3B82F6",
      ["blue-6"]: "#2563EB",
      ["blue-7"]: "#2563EB",
      ["blue-8"]: "#1E40AF",
      ["blue-9"]: "#1E3A8A",
      ["red-5"]: "#EF4444",
      ["green-5"]: "#22C55E",
      ["orange-5"]: "#F97316",
    },
    backgroundImage: {
      wave1: "url('./src/assets/wave_1.svg')",
      loginBg: "url('./src/assets/rm222batch2-mind-03.jpg')",
    },
    extend: {},
  },
  plugins: [],
};
